name: Build

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Cloning repo
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_PRIVATE_PAT }}
        submodules: recursive
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
    - name: Build
      run: hugo --minify --gc
    - uses: EndBug/add-and-commit@v7
      with:
        message: '[ci] compile'
        default_author: github_actions
